<?php

return [
    'GLOBAL' => [
        'PATTERNS' => [
            'PASSWORD' => "/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).+$/",
            'PASSWORD_RULES' => [
                'MIN_LENGTH' => '/^.{8,}$/',
                'UPPERCASE' => '/[A-Z]/',
                'DIGIT' => '/\d/',
                'SPECIAL_CHAR' => '/[@$!%*?&#^(){}[\].]/',
                'COMBINED' => '/^(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&#^(){}[\].]).{8,}$/',
            ],
            'CONTACT_NO' => '/^\d{8,12}$/',
            'MOBILE_NO' => '/^\d{9,10}$/',
            'EMAIL' => " /^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$/i",
            'PHONE' => '/^\d{8,10}$/',
            'NAME' => "/^[^0-9!@#$%^&*()_=+\[\]{}|?<>\/,;:\\\\]+$/",
            'SINGLE_DATE_PATTERN' => "/^\d{4}-\d{2}-\d{2}$/",
            'RANGE_DATE_PATTERN' => "/^\d{4}-\d{2}-\d{2} to \d{4}-\d{2}-\d{2}$/",
            'DISAPPROVAL_REASON_LENGTH' => 500,
            'NAME_LENGTH' => 30,
            'ADDRESS_LENGTH' => 191,
            'MOBILE_EXCEL' => '/^\+?\d[\d\s]{7,12}$/',
            'AUSTRALIAN_MOBILE_NUMBER_LENGTH' => 10,
        ],
        'BACKEND_DATE_FORMAT' => 'Y-m-d',
        'VERIFICATION_TIMER' => 20,
        'ROLES' => [
            'DOCTOR' => 'doctor',
            'ADMIN' => 'admin',
        ],
        'ADMIN_NOTE_TIMEZONE' => 'Australia/Melbourne',
        'DATE_FORMAT_Y_M_D' => 'Y-m-d',
        'DATE_FORMAT_D_M_Y' => 'd-m-Y',
        'DATE_FORMAT_D_F_Y' => 'd F, Y',
        'DATE_FORMAT_M_D_Y' => 'M d, Y',
        'DATE_FORMAT_H_I_A' => 'h:i A',
        'DATE_FORMAT_D_M' => 'd-m',
        'DATE_FORMAT_D_M_Y_H_I_S' => 'd-m-Y H:i:s',
        'DATE_FORMAT_D_M_Y_SLASH' => 'd/m/Y',
        'DATE_FORMAT_M_D_Y' => 'M d, Y',
        'DATE_FORMAT_M_D' => 'M d',
        'VERIFICATION_TIMER' => 20,
        'RESEND_EMAIL_COOLDOWN' => 40,
        'NORMAL_TEXT_LENGTH' => 255,
        'SMS_CONTENT_MIN_LENGTH' => 10,
        'COUNTRY_CODE' => [
            '61',
            '91',
        ],
        'DEFAULT_COUNTRY_CODE' => '61',
        'FILE_TYPE' => [
            'jpg',
            'jpeg',
            'png',
        ],
        'FILE_UPLOAD' => [
            'FOLDERS' => [
                'DRIVING_LICENSE' => 'drivinglicence',
            ],
        ],
        'SOFTWARE' => [
            'DENTAL_4_WINDOWS' => 'Dental 4 Windows',
        ],
        'IMPORT_PATIENT' => [
            'FILE_TYPE' => [
                'xlsx',
                'csv',
                'xls',
            ],
            'FILE_SIZE' => 102400,
            'STATUS' => [
                'PENDING' => 'pending',
                'IN_PROGRESS' => 'in_progress',
                'COMPLETED' => 'completed',
                'FAILED' => 'failed',
                'CANCELLED' => 'cancelled',
            ],
            'TEMP_FILE_FOLDER' => 'imports/temp',
            'COLUMN_MATCHING' => [
                'first_name',
                'last_name',
                'mobile_number',
                'last_recall',
                'insurance',
                'dob',
                'client_patient_id',
            ],
        ],
        'MESSAGE' => [
            'RECALL' => 'recalls',
            'PROMOTIONAL' => 'promotional',
            'CUSTOM' => 'custom',
            'OPT_OUT' => 'opt_out',
            'SEND' => 'send',
            'SENT' => 'sent',
            'FAIL' => 'fail',
            'RECEIVE' => 'receive',
            'INDIVIDUAL' => 'Individual',
        ],
        'INVOICE' => [
            'PAID' => 'paid',
            'ADDITIONAL' => 'additional',
            'SUBSCRIPTION' => 'subscription',
            'OPEN' => 'open',
        ],
        'CAMPAIGN_MESSAGE' => [
            'recalls',
            'promotional',
        ],
        'SUBSCRIPTION_STATUS' => [
            'ACTIVE' => 'active',
        ],
        'CAMPAIGN_STATUS' => [
            'SCHEDULED' => 'scheduled',
            'IN_PROGRESS' => 'in_progress',
            'COMPLETED' => 'completed',
            'CANCELLED' => 'cancelled',
            'DISPATCHED' => 'dispatched',
        ],
        'OTP' => [
            'OTP_EXPIRATION_MINUTES' => 10,
        ],
        'INVOICE_STATUS_LABELS' => [
            'paid' => ['label' => 'Paid', 'color' => 'green'],
            'open' => ['label' => 'Pending', 'color' => 'blue'],
            'fail' => ['label' => 'Payment Failed', 'color' => 'red'],
            'cancel' => ['label' => 'Cancelled', 'color' => 'gray'],
        ],
        'STATES' => [
            [
                'name' => 'New South Wales',
                'code' => 'NSW',
                'timezone' => 'Australia/Sydney',
            ],
            [
                'name' => 'Victoria',
                'code' => 'VIC',
                'timezone' => 'Australia/Melbourne',
            ],
            [
                'name' => 'Queensland',
                'code' => 'QLD',
                'timezone' => 'Australia/Brisbane',
            ],
            [
                'name' => 'South Australia',
                'code' => 'SA',
                'timezone' => 'Australia/Adelaide',
            ],
            [
                'name' => 'Western Australia',
                'code' => 'WA',
                'timezone' => 'Australia/Perth',
            ],
            [
                'name' => 'Tasmania',
                'code' => 'TAS',
                'timezone' => 'Australia/Hobart',
            ],
            [
                'name' => 'Australian Capital Territory',
                'code' => 'ACT',
                'timezone' => 'Australia/Sydney',
            ],
            [
                'name' => 'Northern Territory',
                'code' => 'NT',
                'timezone' => 'Australia/Darwin',
            ],
        ],
    ],
    'CURRENCY' => [
        'Dollar' => '$',
        'CURRENCY_CODE' => env('STRIPE_CURRENCY', 'aud'),
    ],
    'CAMPAIGN_TYPE' => [
        'OVERDUE_RECALLS' => 'Overdue Recalls',
        'PROMOTIONAL'     => 'Promotional',
    ],
    'CLINICS' => [
        'TABS' => [
            'PENDING_APPROVAL' => [
                'label' => 'PENDING_APPROVAL',
                'text'  => 'Pending Approval',
            ],
            'DENIED' => [
                'label' => 'DENIED',
                'text'  => 'Denied',
            ],
            'FREE_TRIAL' => [
                'label' => 'FREE_TRIAL',
                'text'  => 'Free Trial',
            ],
            'SUBSCRIBED_RECENT' => [
                'label' => 'SUBSCRIBED_RECENT',
                'text'  => 'Subscribed',
            ],
            'CANCELLED_OR_PAUSED' => [
                'label' => 'CANCELLED_OR_PAUSED',
                'text'  => 'Cancelled/Paused',
            ],
        ],

        'STATUS' => [
            'APPROVED' => 'approved',
            'DENIED' => 'denied',
            'PENDING' => 'pending',
        ],
        'DENY_REASON' => [
            'PERMANENT_DENIED' => [
                'LABEL' => 'Permanent denied',
                'VALUE' => 'permanent_denied',
            ],
            'REUPLOAD_DOCUMENTS' => [
                'LABEL' => 'Reupload documents',
                'VALUE' => 'reupload_documents',
            ],
        ],
        'DEFAULT_TAB' => 'PENDING_APPROVAL',
        'DEFAULT_AVERAGE_CHECKUP_FEE' => '230',
        'REGISTERED_DATE_TIMEZONE' => 'AEST',
    ],
    'STRIPE' => [
        'WEBHOOK_EVENTS' => [
            'invoice.created',
            'invoice.payment_succeeded',
            'invoice.payment_failed',
        ],
        'PAYMENT_INTENT' => [
            'SUCCEEDED' => 'succeeded',
        ],
        'METER' => [
            'DISPLAY_NAME' => 'Send Sms',
            'EVENT_NAME' => 'send_sms',
            'AGGREGATION_FORMULA' => 'last',
            'VALUE_KEY' => 'value',
            'CUSTOMER_KEY' => 'stripe_customer_id',
        ],
        'PRODUCT' => [
            'NAME' => 'Smileorbit Subscription',
            'DESCRIPTION' => 'Smileorbit Subscription',
        ],
        'TAX' => [
            'NAME' => 'GST',
            'PERCENTAGE' => 10.0,
        ],
    ],
    'CELLCAST' => [
        'WEBHOOK_EVENTS' => [
            'send',
            'receive',
        ],
        'OPT_OUT_MESSAGES' => [
            'stop',
            'unsubscribe',
        ],
    ],
    'POLL_INTERVAL' => 2000,
    'TEMPLATE_LIST_LENGTH' => 10,
    'OVERDUE_TEMPLATE_LIMIT' => 5,
    'PROMOTIONAL_TEMPLATE_LIMIT' => 10,
    'CARD_BRAND_IMAGE_NAME' => [
        'visa' => 'visa.svg',
        'mastercard' => 'master.svg',
        'amex' => 'americanx.svg',
        'jcb' => 'jcb.svg',
        'diners' => 'diners.png',
        'discover' => 'discover.png',
        'eftpos_au' => 'eftpos.svg',
        'unionpay' => 'unionpay.svg',
        'unknown' => 'unknown.svg',
    ],
    'INSURANCE' => [
        'STATUS' => [
            'APPROVED' => 'approved',
            'PENDING' => 'pending',
        ],
    ],
    'TEMPLATE_CATEGORY' => [
        'PREFERRED_PROVIDER' => ['id' => 1, 'name' => 'Preferred Provider', 'priority' => 1],
        'OTHER_INSURANCE' => ['id' => 2, 'name' => 'Other Insurance', 'priority' => 4],
        'CDBC' => ['id' => 3, 'name' => 'CDBS', 'priority' => 2],
        'DVA' => ['id' => 4, 'name' => 'DVA', 'priority' => 3],
        'NO_INSURANCE' => ['id' => 5, 'name' => 'No Insurance', 'priority' => 5],
    ],
    'INSURANCE_TYPES' => [
        'PREFERRED' => 'Preferred',
        'OTHER' => 'Other',
    ],
    'INVOICE_STATUS' => [
        'OPEN' => 'open',
        'FAIL' => 'fail',
        'CANCEL' => 'cancel',
        'PAID' => 'paid',
    ],
    'SUBSCRIPTION_PLAN' => [
        'TYPES' => [
            'FREE' => null,
            'MONTHLY' => 'Monthly',
            'YEARLY' => 'Yearly',
        ],
        'STATUS' => [
            'ACTIVE' => 'active',
            'INACTIVE' => 'inactive',
            'PAYMENT_PENDING' => 'payment_pending',
        ],
        'FREE_PLAN_TYPE_TEXT' => 'Free',
        'CURRENT_STATUS' => [
            'ACTIVE' => 'Active',
            'EXPIRED' => 'Expired',
            'CANCELLED' => 'Cancelled',
        ],
    ],
    'PATIENT' => [
        'STATUS' => [
            'NO_FUTURE_APPOINTMENT' => 'no_future_appointment',
            'BOOKED' => 'booked',
            'OPTED_OUT' => 'opted_out',
            'DEACTIVATED' => 'deactivated',
        ],
        'ACTIVE_STATUS' => [
            'NO_FUTURE_APPOINTMENT' => 'no_future_appointment',
            'BOOKED' => 'booked',
        ],
        'TYPEAHEAD' => [
            'DELAY' => 300,
            'LIMIT' => 10,
            'MIN_LENGTH' => 3,
        ],
        'SMS_SOURCE' => [
            'CLINIC' => 'clinic',
            'ORBIT'  => 'orbit',
        ],
        'ACTIONS' => [
            'COMPLETE' => [
                'label' => 'Completed Appointment',
                'icon' => 'completed-icon.svg',
            ],
            'BOOK' => [
                'label' => 'Booked',
                'icon' => 'calender-icon.svg',
            ],
            'CANCEL' => [
                'label' => 'Cancelled',
                'icon' => 'cancel-icon.svg',
            ],
            'RESCHEDULE' => [
                'label' => 'Rescheduled',
                'icon' => 'reschedule-icon.svg',
            ],
        ],
    ],
    'DATATABLE' => [
        'DATA_NOTE' => '* Indicates SMS was sent by your clinic’s software.',
    ],
    'INVOICE_PDF_FILE_NAME' => 'invoice',
    'BILLING_PERIOD' => 'Monthly',
    'UNIT_PRICE' => '$0.09',
    'INVOICE_DEFAULT_DESCRIPTION' => 'SMS - MOBILE',
    'FOOTER_TEXT' => 'If you have any questions, feel free to email the billing team at',
    'CONTACT_EMAIL' => 'support@smileorbit.com',
    'CONTACT_SUPPORT' => 'https://smileorbit.com/support/',
    'SUBSCRIPTION_PLANS' => [
        ['max_contacts' => 1000, 'price' => 249],
        ['max_contacts' => 2000, 'price' => 329],
        ['max_contacts' => 3000, 'price' => 409],
        ['max_contacts' => 4000, 'price' => 489],
        ['max_contacts' => 5000, 'price' => 569],
        ['max_contacts' => 6000, 'price' => 649],
        ['max_contacts' => 7000, 'price' => 729],
        ['max_contacts' => 8000, 'price' => 809],
        ['max_contacts' => 9000, 'price' => 889],
        ['max_contacts' => 10000, 'price' => 969],
        ['max_contacts' => 11000, 'price' => 1049],
        ['max_contacts' => 12000, 'price' => 1129],
        ['max_contacts' => 13000, 'price' => 1209],
        ['max_contacts' => 14000, 'price' => 1289],
        ['max_contacts' => 15000, 'price' => 1369],
        ['max_contacts' => 16000, 'price' => 1449],
        ['max_contacts' => 17000, 'price' => 1529],
        ['max_contacts' => 18000, 'price' => 1609],
        ['max_contacts' => 19000, 'price' => 1689],
        ['max_contacts' => 20000, 'price' => 1769],
    ],
    'CANCEL_PLAN_AFTER_DAYS' => 21,
    'PAYMENT_FAILED_RESTRICT_AFTER_DAYS' => 21,
    'ADDITIONAL_CHARGE_PER_SMS' => 0.09,
    'ACCESS_AFTER_PLAN_EXPIRE' => 7,
    'FREE_TRIAL_INVOICE_META_DATA_KEY' => 'free_trial_charge',
    'ADDITIONAL_SMS_INVOICE_META_DATA_KEY' => 'additional_sms_charge',
    'ADDITIONAL_SMS_INVOICE_ITEM_DESCRIPTION' => 'Additional Sms Charge',
    'FAILURE_REASON' => [
        'DECLINED' => 'declined',
        '3DS' => '3ds',
    ],
    'FAILED_PAYMENT_REMINDER_DAYS' => [3, 6, 7],
    'TEMPLATE_CATEGORY_TYPES' => [
        'PREFERRED_PROVIDER' => 'Preferred Provider',
        'INSURANCE'          => 'Insurance',
        'CDBC'               => 'CDBC',
        'DVA'                => 'DVA',
        'NO_INSURANCE'       => 'No Insurance',
    ],
    'SPECIAL_INSURANCE' => [
        'CDBS' => 'CDBS',
        'DVA' => 'DVA',
    ],
    'INBOX_CONFIGURATION' => [
        'POLLING_INTERVAL' => 15000,
        'DEBOUNCE_TIMER' => 400,
        'MESSAGE_LENGTH' => 968,
    ],
    'ALLOWED_ROUTES_GRACE' => [
        'subscription.',
        'settings.activity-log.',
        'inbox.index',
        'inbox.list',
        'inbox.chat.history',
        'invoice.',
    ],
    'ALLOWED_ROUTES_AFTER_GRACE' => [
        'subscription.',
        'settings.activity-log.',
        'invoice.',
    ],
    'PAYMENT_FAILED_ACCESS_ROUTE' => [
        'subscription.',
        'inbox.',
        'settings.',
        'patient',
        'patients.',
        'template.',
        'patient.',
        'booked.patient',
        'optedout.patient',
        'deactivate.patient',
        'no_future_appointment.patient',
        'invoice.',
    ],
    'PAYMENT_FAILED_AFTER_SEVEN_DAYS_ACCESS_ROUTE' => [
        'subscription.',
        'settings.activity-log.',
    ],
    'SUBSCRIPTION_ROUTES' => [
        'subscription.',
        'settings.activity-log.',
        'invoice.',
    ],
    'ACCOUNT_SUSPEND_ACCESS_ROUTE' => [
        'subscription.',
        'invoice.',
        'settings.activity-log.',
        'settings.activity.',
        'inbox.index',
        'inbox.list',
        'inbox.chat.history',
    ],
    'ALLOWED_DAYS_AFTER_CANCELLATION' => 21,
    'MESSAGE_BLOCK_SIZE' => 100,
    'ACTIVITY_LOG' => [
        'EVENT_DISPLAY' => [
            'PATIENT_UPDATED' => 'Patient Updated',
            'IMPORT_CSV' => 'Imported CSV',
            'SMS' => 'SMS',
            'TEMPLATE_CREATED' => 'Template Created',
            'TEMPLATE_UPDATED' => 'Template Updated',
            'TEMPLATE_DELETED' => 'Template Deleted',
            'DEACTIVATED' => 'Deactivated',
            'OPT_IN' => 'Imported CSV',
            'OPT_OUT' => 'opt-out',
        ],
        'EXPORT_STATUS' => [
            'PENDING' => 'pending',
            'PROCESSING' => 'processing',
            'COMPLETED' => 'completed',
            'READY_FOR_DOWNLOAD' => 'ready_for_download',
            'FAILED' => 'failed',
        ],
    ],
    'CAMPAIGN_EXPIRY_MINUTES' => 30,
    'TEMPLATE_ALLOW_DYNAMIC_FIELDS' => [
        'First Name',
        'Last Name',
        'Clinic Name',
        'Online Booking Link',
        'Clinic Phone Number',
        'Date of Last Recall',
        'Insurance',
    ],
    'QUICK_RECALL_SMS' => [
        'LIMIT' => 25,
        'RECALL_MONTHS' => 6,
    ],
    'SMILE_ORBIT_ABN' => '36660679327',
    'CREDIT_RENEW_NOTIFICATION_DAYS' => 7,
    'UNUSED_SEGMENTS_THRESHOLD' => 50,
    'MAX_LENGTH' => [
        'FIRST_NAME' => 50,
        'LAST_NAME' => 50,
        'EMAIL' => 255,
        'COMPANY_ABN' => 11,
        'CLINIC_NAME' => 50,
        'COMPANY_NAME' => 50,
        'ADDRESS' => 191,
        'FULL_NAME' => 100,
        'MOBILE' => 10,
        'CONTACT' => 12,
        'TEMPLATE_NAME' => 50,
        'TEMPLATE_MESSAGE' => 968,
        'INBOX_MESSAGE' => 968,
        'OTHER_SOFTWARE' => 255,
        'ABBREVIATION' => 20,
        'COMMON_NAME' => 50,
        'PASSWORD' => 50,
        'OTP' => 6,
        'EXCEL' => [
            'MOBILE' => 20,
            'DATE_FIELDS' => 10,
        ],
    ],
    'NOTIFICATIONS' => [
        'TYPE' => [
            'SUCCESS' => ['text' => 'success', 'image' => 'green-tick-mark.svg'],
            'WARNING' => ['text' => 'warning', 'image' => 'orange-warning-icon.svg'],
            'ERROR' => ['text' => 'error', 'image' => 'orange-warning-icon.svg'],
            'REMINDER' => ['text' => 'reminder', 'image' => 'blue-notification-icon.svg'],
            'NUDGE' => ['text' => 'nudge', 'image' => 'blue-notification-icon.svg'],
        ],
        'NAME' => [
            'PATIENT_LIST_IMPORTED_SUCCESSFULLY' => 'Patient List Imported Successfully',
            'PROMOTIONAL_CAMPAIGN_SENT' => 'Promotional Campaign Sent',
            'OVERDUE_RECALL_CAMPAIGN_SENT' => 'Overdue Recall Campaign Sent',
            'MONTHLY_SMS_CREDITS_RENEWED' => 'Monthly SMS Credits Renewed',
            'SMS_USAGE_75_PERCENT_ALERT' => '75% SMS usage alert',
            'SMS_USAGE_100_PERCENT_ALERT' => '100% SMS usage alert',
            'CAMPAIGN_CANCELLED_SYSTEM_ISSUE' => 'Campaign cancelled (system issue)',
            'NO_CAMPAIGNS_SENT_2_WEEKS' => 'No campaigns sent (2 weeks into billing cycle)',
            'LAST_DATA_SYNC_2_WEEKS_AGO' => 'Last data sync over 2 weeks ago',
            'LOW_USAGE_REMINDER_50_PERCENT_UNUSED' => 'Low usage reminder (more than 50% SMS unused, 7 days left)',
        ],
    ],
    'NOTE_ACTIVITY' => [
        'APPROVE' => 'approve',
        'DENY' => 'deny',
        'SUSPEND' => 'suspend',
        'REACTIVATE' => 'reactivate',
    ],
    'NOTE_TIMESTAMP_TIMEZONE' => 'Australia/Melbourne',
    'NO_CAMPAIGN_REMINDER_DAYS' => 14,
    'NO_IMPORT_REMINDER_DAYS' => 14,
    'IMPORT_PATIENT_MAX_LIMIT' => 20000,
    'CANCEL_GRACE_DAYS' => 14,
    'SUBSCRIPTION_EXTENSION_DAYS' => 7,
    'FAILED_PAYMENT_GRACE_DAYS' => 22,

];
